[Docu] Quantity Price Rules
coreshop/CoreShop pull request #1716
Opened 2021-08-23 14:03 UTC by lukadschaak

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -

Documenting the usage of quantity price rules.

With help by @Theux94

2021-08-24 06:11 UTC, dpfaffenbauer requested changes

2021-08-24 06:11 UTC, dpfaffenbauer commented on docs/02_User_Documentation/03_Price_Rules/03_Specific_Price_Rules.md
> +It is recommended to have at least one specific price, which is always applicable. For example a
it is not, why should it?

2021-08-24 06:11 UTC, dpfaffenbauer commented on docs/02_User_Documentation/03_Price_Rules/04_Quantity_Price_Rules.md
> +but to have at least a default specific price (or a store values entry).
Don't recommend things here.

2021-08-24 06:11 UTC, dpfaffenbauer commented on docs/03_Development/03_Products/02_Price_Calculation.md
> +To get a non-zero price, the calculation needs at least a matching specific price rule, or a store value to work.
please remove. the default is ALWAYS to have a store-value. price

2021-08-24 14:21 UTC, lukadschaak commented
Updated, please check changes.

2021-09-06 09:35 UTC, lukadschaak commented
*push* @dpfaffenbauer Still interested in this part of documentation?

2021-09-06 12:07 UTC, dpfaffenbauer commented
@lukadschaak yes, sorry, I am on holiday right now and had lots todo before I left. Will review this when I am back.

2021-09-06 14:02 UTC, lukadschaak commented
Ohh holiday is nice! Keep on refreshing!! :)

2021-09-13 08:42 UTC, dpfaffenbauer approved these changes

2021-09-13 08:42 UTC, merged

2021-09-13 08:42 UTC, dpfaffenbauer commented
thanks a lot