Cart update and checkout validation for cart
coreshop/CoreShop pull request #1920
Opened 2022-03-22 07:39 UTC by BabovicT

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 

It was possible to update the cart from cart summary view without form validation being triggered. For some reason cart validation is not working there but new Order one is. 
Also there was no cart validation on first checkout step and you were able to order more products than there is.

2022-03-22 13:20 UTC, dpfaffenbauer requested changes

2022-03-22 13:20 UTC, dpfaffenbauer commented on src/CoreShop/Bundle/CoreBundle/Checkout/Step/CustomerCheckoutStep.php
> +use CoreShop\Component\Inventory\Checker\AvailabilityCheckerInterface;
not needed

2022-03-22 13:41 UTC, BabovicT commented on src/CoreShop/Bundle/FrontendBundle/Controller/CheckoutController.php
> +            if (!$this->availabilityChecker->isStockSufficient($item->getProduct(), 0)) {
I will remove it. Not necessary anymore

2022-03-23 08:22 UTC, dpfaffenbauer commented on src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
> +        $cloneCart = clone($cart);
Problem is that validation fails cart shows wrong information?

2022-03-23 08:41 UTC, BabovicT commented on src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
> +        $cloneCart = clone($cart);
Yes. If we have 1 item in cart and that 1 is last item available and we try to add one more then:
If there is no form copy cart will show 2.
If there is form copy cart will show 1.
In both cases error is shown and cart resets to 1 after submit and going to next step.

2022-03-23 10:23 UTC, BabovicT commented on src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
> +        $cloneCart = clone($cart);
Cart item in both cart and form is with new invalid quantity. Only cart object is loaded from database.

2022-03-24 09:02 UTC, BabovicT commented
@dpfaffenbauer seems to be working :)

2022-03-24 09:21 UTC, dpfaffenbauer approved these changes

2022-03-24 09:21 UTC, merged