Add submit buttons for voucher submit and form update in cart form
coreshop/CoreShop pull request #1950
Opened 2022-04-04 21:12 UTC by breakone

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #...

2022-04-05 05:48 UTC, dpfaffenbauer requested changes

2022-04-05 05:48 UTC, dpfaffenbauer commented on src/CoreShop/Bundle/FrontendBundle/Controller/CartController.php
> +                $submit = $form->getClickedButton();
check if $form is instanceof Form or method_exists('getClickedButton')

2022-04-06 08:28 UTC, breakone commented
@dpfaffenbauer 
checked, if method "getClickedButton" exists and use fallback if not

2022-04-07 09:28 UTC, dpfaffenbauer approved these changes

2022-04-07 09:28 UTC, merged