C r w fix non unique typename
coreshop/CoreShop pull request #2004
Opened 2022-05-19 09:16 UTC by C-R-W

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #...   

Fix non unique type name.

Bug:
If there is more then one SerializedDataType in a schema entity a exception gets thrown.

Uncaught PHP Exception GraphQL\Error\InvariantViolation: "Schema must contain unique named types but contains multiple types named "coreShopSerializedData" (see http://webonyx.github.io/graphql-php/type-system/#type-registry)." at /var/www/vhosts/portal.prooptik.de/pimcore-live/vendor/webonyx/graphql-php/src/Utils/Utils.php line 333 {"exception":"[object] (GraphQL\\Error\\InvariantViolation(code: 0): Schema must contain unique named types but contains multiple types named \"coreShopSerializedData\" (see http://webonyx.github.io/graphql-php/type-system/#type-registry). at /var/www/vhosts/portal.prooptik.de/pimcore-live/vendor/webonyx/graphql-php/src/Utils/Utils.php:333)"

2022-05-19 09:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/coreshop/CoreShop?pullRequest=2004) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/coreshop/CoreShop?pullRequest=2004) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/coreshop/CoreShop?pullRequest=2004) it.</sub>

2022-05-23 05:35 UTC, dpfaffenbauer commented
@C-R-W please sign the CLA and check why tests are failing now

2022-06-09 06:23 UTC, dpfaffenbauer requested changes

2022-06-09 06:23 UTC, dpfaffenbauer commented on src/CoreShop/Bundle/PimcoreBundle/DataHub/Type/SerializedDataType.php
> +use Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\GeopointType;
not needed here. pelase remove

2022-06-09 06:23 UTC, dpfaffenbauer commented on src/CoreShop/Bundle/PimcoreBundle/DataHub/QueryType/SerializedData.php
> +        return SerializedDataType::getInstance();
don't use a singleton here, rather create the instance here and keep it.

2022-06-09 06:23 UTC, dpfaffenbauer commented
@C-R-W Tests fail for other reasons, I still have some comments

2022-07-06 16:01 UTC, C-R-W commented
Hi, i updated the files, is this ok so?

2022-07-07 05:39 UTC, dpfaffenbauer requested changes

2022-07-07 05:39 UTC, dpfaffenbauer commented on src/CoreShop/Bundle/PimcoreBundle/DataHub/QueryType/SerializedData.php
> +use phpDocumentor\Reflection\Types\Self_;
what is this?

2022-07-07 06:11 UTC, C-R-W commented on src/CoreShop/Bundle/PimcoreBundle/DataHub/QueryType/SerializedData.php
> +use phpDocumentor\Reflection\Types\Self_;
sorry, just removed it.

2022-08-24 07:47 UTC, dpfaffenbauer approved these changes

2022-08-24 08:16 UTC, merged

2022-08-24 08:17 UTC, dpfaffenbauer commented
thanks @C-R-W