Make URL slugs overwritable
coreshop/CoreShop pull request #2236
Opened 2023-03-22 10:35 UTC by BlackbitDevs

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? |no

Currently the URL slugs are always regenerated during saving. There is no way to manually change a URL. 
Even worse, in https://github.com/coreshop/CoreShop/blob/75d7f0b2e8d72b9537c948d896c8e6d2e27bd356/src/CoreShop/Component/Pimcore/Slug/DataObjectSlugGenerator.php#L67-L68
`$newSlug` is the generated one and `$existingSlug` is the one which may have been changed with the objects setter method (`$sluggable->setSlug()`). 
Example:
I have a product with `name=my product` and set the slug in the pimcore backend to be `/en/product-123`. When this gets saved, the slug `/en/my-product` gets generated. With above code not only the manually set slug gets reset to `/en/my-product` but moreover there will also be a redirect generated for `/en/product-123` to `/en/my-product`.

With this PR the URL slug gets generated if none exists but it does not use the generated one when there already is a slug set.

2023-03-22 10:37 UTC, dpfaffenbauer requested changes

2023-03-22 10:37 UTC, dpfaffenbauer commented on src/CoreShop/Component/Pimcore/Slug/DataObjectSlugGenerator.php
> +            $inheritanceEnabled = AbstractObject::getGetInheritedValues();
use CoreShops Inheritance Helper

2023-03-22 10:45 UTC, BlackbitDevs commented on src/CoreShop/Component/Pimcore/Slug/DataObjectSlugGenerator.php
> +            $inheritanceEnabled = AbstractObject::getGetInheritedValues();
Thx, done.

2023-03-22 10:59 UTC, BlackbitDevs commented
@dpfaffenbauer What do you think about PhpStan complaining about `Call to an undefined method CoreShop\Component\Pimcore\Slug\SluggableInterface::retrieveSlugData()`? This is a Pimcore core method https://github.com/pimcore/pimcore/blob/765832f0dc5f6cfb296a82e089b701066f27bcef/models/DataObject/Concrete.php#L849 - add it to the `SluggableInterface`?

2023-03-22 14:49 UTC, solverat commented
Related issue: https://github.com/coreshop/CoreShop/issues/2198

2023-03-22 21:49 UTC, jdreesen commented on src/CoreShop/Component/Pimcore/Slug/DataObjectSlugGenerator.php
> +            }, false);
```suggestion
            $existingSlugs = InheritanceHelper::useInheritedValues(
                fn () => $sluggable->getSlug($language),
                false,
            );
```

2023-03-23 06:52 UTC, dpfaffenbauer commented
@BlackbitDevs adding the function to the SluggableInterface also means that "parent" classes need to implement it. What if we type check for Concrete?

2023-03-23 06:55 UTC, BlackbitDevs commented
> @BlackbitDevs adding the function to the SluggableInterface also means that "parent" classes need to implement it. What if we type check for Concrete?

Perfectly fine for me ;)
Will adjust the code.

2023-04-07 07:15 UTC, dpfaffenbauer commented
@BlackbitDevs can you check the tests pls?

2023-04-13 08:37 UTC, BlackbitDevs commented
Ok, the remaining Psalm error is
`InternalMethod - src/CoreShop/Component/Pimcore/Slug/DataObjectSlugGenerator.php:73:55 - The method Pimcore\Model\DataObject\Concrete::retrieveSlugData is internal to Pimcore but called from CoreShop\Component\Pimcore\Slug\DataObjectSlugGenerator::generateSlugs`
What to do? Copy the method to Coreshop? Or ask Pimcore to remov the `@internal`?

2023-04-13 08:54 UTC, dpfaffenbauer commented
@BlackbitDevs  ```/** @psalm-suppress InternalMethod */```

2023-04-19 15:12 UTC, merged

2023-04-19 15:12 UTC, dpfaffenbauer commented
thanks a lot @BlackbitDevs