[VariantBundle] Add possibility to exclude Variants from AttributeCollector via AttributePreconditionEvent
coreshop/CoreShop pull request #2674
Opened 2024-08-05 15:15 UTC by almshadi

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no

2024-08-05 15:21 UTC, jdreesen commented on src/CoreShop/Component/Variant/AttributeCollector.php
> +                    $this->eventDispatcher->dispatch($event = new variantAvailabilityEvent($product), 'coreshop.attribute.collector.preCondition');
```suggestion
                    $event = $this->eventDispatcher->dispatch(new variantAvailabilityEvent($product), 'coreshop.attribute.collector.preCondition');
```

2024-08-05 15:21 UTC, jdreesen commented on src/CoreShop/Component/Variant/Event/variantAvailabilityEvent.php
> +class variantAvailabilityEvent extends Event
```suggestion
class VariantAvailabilityEvent extends Event
```

The file also needs to be renamed.

2024-08-05 15:28 UTC, jdreesen commented on src/CoreShop/Component/Variant/Event/variantAvailabilityEvent.php
The file name still starts with a lower case letter.

2024-08-05 15:33 UTC, dpfaffenbauer commented on src/CoreShop/Component/Variant/Event/variantAvailabilityEvent.php
@almshadi please fix that

2024-08-06 08:15 UTC, almshadi commented on src/CoreShop/Component/Variant/Event/variantAvailabilityEvent.php
done

2024-08-06 08:16 UTC, dpfaffenbauer approved these changes

2024-08-06 08:52 UTC, dpfaffenbauer requested changes

2024-08-06 08:52 UTC, dpfaffenbauer commented on src/CoreShop/Component/Variant/Event/VariantAvailabilityEvent.php
> +    public function __construct(private ProductInterface $product)
@almshadi Use VariantAwareInterface here

2024-08-07 10:45 UTC, almshadi commented on src/CoreShop/Component/Variant/Event/VariantAvailabilityEvent.php
> +    public function __construct(private ProductInterface $product)
fixed

2024-08-07 11:18 UTC, dpfaffenbauer approved these changes

2024-08-07 11:18 UTC, merged

2024-08-07 11:18 UTC, dpfaffenbauer commented
🎉